# Generated by Django 4.1.5 on 2024-01-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeesalary_alter_employee_department_and_more'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employee.employee'),
        ),
    ]
